"""
darave_rl/batch.py — AudioBatch data container for RL training.

Holds one batch of transitions with real audio, agent actions, generated
audio, features, rewards, and state transitions.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Dict

import numpy as np


@dataclass
class AudioBatch:
    """
    A batch of transition data for RL training.

    All arrays have batch dimension B as first axis.

    Attributes
    ----------
    real_audio : np.ndarray, shape [B, T]
        Real transition audio segments (Song A exit / Song B entry).
    real_features : np.ndarray, shape [B, F_real]
        Feature vectors extracted from real audio.
    actions : np.ndarray, shape [B, action_dim]
        Action vectors produced by the policy.
    synth_audio : np.ndarray, shape [B, T]
        Audio generated by the synth engine from the agent's actions.
    synth_features : np.ndarray, shape [B, F_synth]
        Feature vectors extracted from generated audio.
    rewards : np.ndarray, shape [B]
        Scalar reward for each transition.
    user_scores : np.ndarray, shape [B]
        Human feedback scores (0 if unavailable).
    states : np.ndarray, shape [B, obs_dim]
        Observation vectors before the action.
    next_states : np.ndarray, shape [B, obs_dim]
        Observation vectors after the action.
    dones : np.ndarray, shape [B]
        Episode termination flags (1.0 = done).
    """

    real_audio: np.ndarray
    real_features: np.ndarray
    actions: np.ndarray
    synth_audio: np.ndarray
    synth_features: np.ndarray
    rewards: np.ndarray
    user_scores: np.ndarray
    states: np.ndarray
    next_states: np.ndarray
    dones: np.ndarray

    def __len__(self) -> int:
        return len(self.states)

    @property
    def obs_dim(self) -> int:
        return self.states.shape[1] if self.states.ndim > 1 else 1

    @property
    def action_dim(self) -> int:
        return self.actions.shape[1] if self.actions.ndim > 1 else 1

    @property
    def batch_size(self) -> int:
        return len(self.states)

    def to_dict(self) -> Dict[str, np.ndarray]:
        """Convert to dict for easy serialization / torch conversion."""
        return {
            "real_audio": self.real_audio,
            "real_features": self.real_features,
            "actions": self.actions,
            "synth_audio": self.synth_audio,
            "synth_features": self.synth_features,
            "rewards": self.rewards,
            "user_scores": self.user_scores,
            "states": self.states,
            "next_states": self.next_states,
            "dones": self.dones,
        }

    def split(self, n_chunks: int) -> list:
        """Split batch into n_chunks sub-batches along batch dimension."""
        chunks = []
        size = len(self) // n_chunks
        for i in range(n_chunks):
            s = i * size
            e = s + size if i < n_chunks - 1 else len(self)
            chunks.append(
                AudioBatch(
                    real_audio=self.real_audio[s:e],
                    real_features=self.real_features[s:e],
                    actions=self.actions[s:e],
                    synth_audio=self.synth_audio[s:e],
                    synth_features=self.synth_features[s:e],
                    rewards=self.rewards[s:e],
                    user_scores=self.user_scores[s:e],
                    states=self.states[s:e],
                    next_states=self.next_states[s:e],
                    dones=self.dones[s:e],
                )
            )
        return chunks

    def shuffle(self, rng: np.random.Generator = None) -> "AudioBatch":
        """Return a shuffled copy of the batch."""
        if rng is None:
            rng = np.random.default_rng()
        idx = rng.permutation(len(self))
        return AudioBatch(
            real_audio=self.real_audio[idx],
            real_features=self.real_features[idx],
            actions=self.actions[idx],
            synth_audio=self.synth_audio[idx],
            synth_features=self.synth_features[idx],
            rewards=self.rewards[idx],
            user_scores=self.user_scores[idx],
            states=self.states[idx],
            next_states=self.next_states[idx],
            dones=self.dones[idx],
        )

    @classmethod
    def empty(cls, obs_dim: int = 71, action_dim: int = 26) -> "AudioBatch":
        """Create an empty batch with zero samples."""
        return cls(
            real_audio=np.zeros((0, 0), dtype=np.float32),
            real_features=np.zeros((0, 0), dtype=np.float32),
            actions=np.zeros((0, action_dim), dtype=np.float32),
            synth_audio=np.zeros((0, 0), dtype=np.float32),
            synth_features=np.zeros((0, 0), dtype=np.float32),
            rewards=np.zeros(0, dtype=np.float32),
            user_scores=np.zeros(0, dtype=np.float32),
            states=np.zeros((0, obs_dim), dtype=np.float32),
            next_states=np.zeros((0, obs_dim), dtype=np.float32),
            dones=np.zeros(0, dtype=np.float32),
        )

    @classmethod
    def from_episodes(cls, episodes: list) -> "AudioBatch":
        """
        Collate a list of DjTransitionEpisode objects into one AudioBatch.

        Episodes must have non-empty action_vec, features_real, features_mix,
        and audio_mix fields.
        """
        if not episodes:
            return cls.empty()

        actions = np.stack([ep.action_vec for ep in episodes])
        states = np.stack([ep.features_real for ep in episodes])
        next_states = np.stack([ep.features_mix for ep in episodes])
        rewards = np.array([ep.r_total for ep in episodes], dtype=np.float32)
        user_scores = np.array(
            [ep.user_score_raw if ep.user_score_raw is not None else 0.0 for ep in episodes],
            dtype=np.float32,
        )
        dones = np.ones(len(episodes), dtype=np.float32)  # each episode is a single step

        # Audio arrays — pad to max length in batch
        max_audio_len = max(
            max(e.real_before.size, e.real_after.size, e.audio_mix.size) for e in episodes
        )
        max_audio_len = max(max_audio_len, 1)
        real_audio = np.stack([_pad_to(ep.audio_mix, max_audio_len) for ep in episodes])
        real_features = states.copy()
        synth_features = next_states.copy()
        synth_audio = real_audio.copy()

        return cls(
            real_audio=real_audio,
            real_features=real_features,
            actions=actions,
            synth_audio=synth_audio,
            synth_features=synth_features,
            rewards=rewards,
            user_scores=user_scores,
            states=states,
            next_states=next_states,
            dones=dones,
        )


def _pad_to(arr: np.ndarray, target_len: int) -> np.ndarray:
    """Pad 1D array with zeros to target length."""
    if arr.size == 0:
        return np.zeros(target_len, dtype=np.float32)
    if len(arr) >= target_len:
        return arr[:target_len]
    return np.concatenate([arr, np.zeros(target_len - len(arr), dtype=arr.dtype)])
